// <auto-generated />
using System;
using ImovelStand.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImovelStand.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260422000719_MultiTenantCore")]
    partial class MultiTenantCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImovelStand.Domain.Entities.Apartamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Orientacao")
                        .HasColumnType("int");

                    b.Property<int>("Pavimento")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecoAtual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipologiaId")
                        .HasColumnType("int");

                    b.Property<int>("TorreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipologiaId");

                    b.HasIndex("TorreId", "Numero")
                        .IsUnique();

                    b.ToTable("Apartamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0101",
                            Orientacao = 0,
                            Pavimento = 1,
                            PrecoAtual = 350000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 2,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0102",
                            Orientacao = 1,
                            Pavimento = 1,
                            PrecoAtual = 520000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 3,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0201",
                            Orientacao = 0,
                            Pavimento = 2,
                            PrecoAtual = 353500.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 4,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0202",
                            Orientacao = 1,
                            Pavimento = 2,
                            PrecoAtual = 525200.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 5,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0301",
                            Orientacao = 0,
                            Pavimento = 3,
                            PrecoAtual = 357000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 6,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0302",
                            Orientacao = 1,
                            Pavimento = 3,
                            PrecoAtual = 530400.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 7,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0401",
                            Orientacao = 0,
                            Pavimento = 4,
                            PrecoAtual = 360500.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 8,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0402",
                            Orientacao = 1,
                            Pavimento = 4,
                            PrecoAtual = 535600.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 9,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0501",
                            Orientacao = 0,
                            Pavimento = 5,
                            PrecoAtual = 364000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 10,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0502",
                            Orientacao = 1,
                            Pavimento = 5,
                            PrecoAtual = 540800.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 11,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0601",
                            Orientacao = 0,
                            Pavimento = 6,
                            PrecoAtual = 367500.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 12,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0602",
                            Orientacao = 1,
                            Pavimento = 6,
                            PrecoAtual = 546000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 13,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0701",
                            Orientacao = 0,
                            Pavimento = 7,
                            PrecoAtual = 371000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 14,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0702",
                            Orientacao = 1,
                            Pavimento = 7,
                            PrecoAtual = 551200.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 15,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0801",
                            Orientacao = 0,
                            Pavimento = 8,
                            PrecoAtual = 374500.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 16,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0802",
                            Orientacao = 1,
                            Pavimento = 8,
                            PrecoAtual = 556400.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 17,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0901",
                            Orientacao = 0,
                            Pavimento = 9,
                            PrecoAtual = 378000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 18,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0902",
                            Orientacao = 1,
                            Pavimento = 9,
                            PrecoAtual = 561600.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 19,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "1001",
                            Orientacao = 0,
                            Pavimento = 10,
                            PrecoAtual = 381500.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 20,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "1002",
                            Orientacao = 1,
                            Pavimento = 10,
                            PrecoAtual = 566800.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 21,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "1101",
                            Orientacao = 0,
                            Pavimento = 11,
                            PrecoAtual = 385000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 22,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "1102",
                            Orientacao = 1,
                            Pavimento = 11,
                            PrecoAtual = 572000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 23,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "1201",
                            Orientacao = 0,
                            Pavimento = 12,
                            PrecoAtual = 1332000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 3,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 24,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "1202",
                            Orientacao = 1,
                            Pavimento = 12,
                            PrecoAtual = 1332000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 3,
                            TorreId = 1
                        },
                        new
                        {
                            Id = 25,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0101",
                            Orientacao = 0,
                            Pavimento = 1,
                            PrecoAtual = 350000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 26,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0102",
                            Orientacao = 1,
                            Pavimento = 1,
                            PrecoAtual = 520000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 27,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0201",
                            Orientacao = 0,
                            Pavimento = 2,
                            PrecoAtual = 353500.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 28,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0202",
                            Orientacao = 1,
                            Pavimento = 2,
                            PrecoAtual = 525200.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 29,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0301",
                            Orientacao = 0,
                            Pavimento = 3,
                            PrecoAtual = 357000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 30,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0302",
                            Orientacao = 1,
                            Pavimento = 3,
                            PrecoAtual = 530400.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 31,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0401",
                            Orientacao = 0,
                            Pavimento = 4,
                            PrecoAtual = 360500.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 32,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0402",
                            Orientacao = 1,
                            Pavimento = 4,
                            PrecoAtual = 535600.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 33,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0501",
                            Orientacao = 0,
                            Pavimento = 5,
                            PrecoAtual = 364000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 34,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0502",
                            Orientacao = 1,
                            Pavimento = 5,
                            PrecoAtual = 540800.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 35,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0601",
                            Orientacao = 0,
                            Pavimento = 6,
                            PrecoAtual = 367500.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 36,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0602",
                            Orientacao = 1,
                            Pavimento = 6,
                            PrecoAtual = 546000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 37,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0701",
                            Orientacao = 0,
                            Pavimento = 7,
                            PrecoAtual = 371000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 38,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0702",
                            Orientacao = 1,
                            Pavimento = 7,
                            PrecoAtual = 551200.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 39,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0801",
                            Orientacao = 0,
                            Pavimento = 8,
                            PrecoAtual = 374500.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 40,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0802",
                            Orientacao = 1,
                            Pavimento = 8,
                            PrecoAtual = 556400.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 41,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0901",
                            Orientacao = 0,
                            Pavimento = 9,
                            PrecoAtual = 378000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 42,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "0902",
                            Orientacao = 1,
                            Pavimento = 9,
                            PrecoAtual = 561600.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 43,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "1001",
                            Orientacao = 0,
                            Pavimento = 10,
                            PrecoAtual = 381500.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 44,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "1002",
                            Orientacao = 1,
                            Pavimento = 10,
                            PrecoAtual = 566800.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 45,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "1101",
                            Orientacao = 0,
                            Pavimento = 11,
                            PrecoAtual = 385000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 1,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 46,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "1102",
                            Orientacao = 1,
                            Pavimento = 11,
                            PrecoAtual = 572000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 2,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 47,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "1201",
                            Orientacao = 0,
                            Pavimento = 12,
                            PrecoAtual = 1332000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 3,
                            TorreId = 2
                        },
                        new
                        {
                            Id = 48,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Numero = "1202",
                            Orientacao = 1,
                            Pavimento = 12,
                            PrecoAtual = 1332000.00m,
                            Status = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TipologiaId = 3,
                            TorreId = 2
                        });
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Cpf")
                        .IsUnique();

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Empreendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Construtora")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DataEntregaPrevista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("VgvEstimado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique();

                    b.ToTable("Empreendimentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Construtora = "Construtora Demo Ltda",
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataEntregaPrevista = new DateTime(2027, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataLancamento = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Empreendimento demo para ambiente de desenvolvimento",
                            Nome = "Residencial Exemplo",
                            Slug = "residencial-exemplo",
                            Status = 1,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            VgvEstimado = 38000000m
                        });
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EntidadeId")
                        .HasColumnType("int");

                    b.Property<int>("EntidadeTipo")
                        .HasColumnType("int");

                    b.Property<string>("Legenda")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EntidadeTipo", "EntidadeId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.HistoricoPreco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlteradoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ApartamentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PrecoAnterior")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoNovo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApartamentoId");

                    b.ToTable("HistoricoPrecos");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("FeaturesJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MaxEmpreendimentos")
                        .HasColumnType("int");

                    b.Property<int>("MaxUnidades")
                        .HasColumnType("int");

                    b.Property<int>("MaxUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrecoMensal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Planos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            MaxEmpreendimentos = 1,
                            MaxUnidades = 100,
                            MaxUsuarios = 3,
                            Nome = "Starter",
                            PrecoMensal = 299m
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            MaxEmpreendimentos = 5,
                            MaxUnidades = 500,
                            MaxUsuarios = 15,
                            Nome = "Pro",
                            PrecoMensal = 899m
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            MaxEmpreendimentos = 50,
                            MaxUnidades = 10000,
                            MaxUsuarios = 100,
                            Nome = "Business",
                            PrecoMensal = 2499m
                        });
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartamentoId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Ativa");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApartamentoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AtivoAte")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PlanoId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TrialAte")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("[Cnpj] IS NOT NULL");

                    b.HasIndex("PlanoId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Ativo = true,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Imobiliária Demo",
                            PlanoId = 2,
                            Slug = "demo"
                        });
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Tipologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaPrivativa")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AreaTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Banheiros")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlantaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PrecoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quartos")
                        .HasColumnType("int");

                    b.Property<int>("Suites")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Vagas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpreendimentoId", "Nome")
                        .IsUnique();

                    b.ToTable("Tipologias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaPrivativa = 55m,
                            AreaTotal = 70m,
                            Banheiros = 1,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmpreendimentoId = 1,
                            Nome = "2Q Garden",
                            PrecoBase = 350000m,
                            Quartos = 2,
                            Suites = 0,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Vagas = 1
                        },
                        new
                        {
                            Id = 2,
                            AreaPrivativa = 75m,
                            AreaTotal = 95m,
                            Banheiros = 2,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmpreendimentoId = 1,
                            Nome = "3Q Suite",
                            PrecoBase = 520000m,
                            Quartos = 3,
                            Suites = 1,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Vagas = 2
                        },
                        new
                        {
                            Id = 3,
                            AreaPrivativa = 140m,
                            AreaTotal = 180m,
                            Banheiros = 3,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmpreendimentoId = 1,
                            Nome = "Cobertura Duplex",
                            PrecoBase = 1200000m,
                            Quartos = 3,
                            Suites = 2,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Vagas = 2
                        });
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Torre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartamentosPorPavimento")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("EmpreendimentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Pavimentos")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmpreendimentoId", "Nome")
                        .IsUnique();

                    b.ToTable("Torres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApartamentosPorPavimento = 2,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmpreendimentoId = 1,
                            Nome = "Torre A",
                            Pavimentos = 12,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            ApartamentosPorPavimento = 2,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmpreendimentoId = 1,
                            Nome = "Torre B",
                            Pavimentos = 12,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Corretor");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@imovelstand.com",
                            Nome = "Administrador",
                            Role = "Admin",
                            SenhaHash = "$2a$11$r4aHE2PnR4xi9noJxkzqe.2SIC5DqPZvinTi8EmFOHsMRIWcrPkqi",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCadastro = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "corretor@imovelstand.com",
                            Nome = "Corretor Teste",
                            Role = "Corretor",
                            SenhaHash = "$2a$11$D8sg3FrM1EI689Z905iG2ubYw/m6LSlI3au9TWZFWd9dCFhw9rxQS",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartamentoId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Concluída");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorEntrada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApartamentoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Apartamento", b =>
                {
                    b.HasOne("ImovelStand.Domain.Entities.Tipologia", "Tipologia")
                        .WithMany("Apartamentos")
                        .HasForeignKey("TipologiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImovelStand.Domain.Entities.Torre", "Torre")
                        .WithMany("Apartamentos")
                        .HasForeignKey("TorreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tipologia");

                    b.Navigation("Torre");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Empreendimento", b =>
                {
                    b.OwnsOne("ImovelStand.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("EmpreendimentoId")
                                .HasColumnType("int");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("nvarchar(9)");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)");

                            b1.HasKey("EmpreendimentoId");

                            b1.ToTable("Empreendimentos");

                            b1.WithOwner()
                                .HasForeignKey("EmpreendimentoId");

                            b1.HasData(
                                new
                                {
                                    EmpreendimentoId = 1,
                                    Bairro = "Centro",
                                    Cep = "01000-000",
                                    Cidade = "Sao Paulo",
                                    Logradouro = "Avenida Demo",
                                    Numero = "1000",
                                    Uf = "SP"
                                });
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.HistoricoPreco", b =>
                {
                    b.HasOne("ImovelStand.Domain.Entities.Apartamento", "Apartamento")
                        .WithMany("HistoricoPrecos")
                        .HasForeignKey("ApartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartamento");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("ImovelStand.Domain.Entities.Apartamento", "Apartamento")
                        .WithMany("Reservas")
                        .HasForeignKey("ApartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImovelStand.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartamento");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Tenant", b =>
                {
                    b.HasOne("ImovelStand.Domain.Entities.Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Tipologia", b =>
                {
                    b.HasOne("ImovelStand.Domain.Entities.Empreendimento", "Empreendimento")
                        .WithMany("Tipologias")
                        .HasForeignKey("EmpreendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empreendimento");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Torre", b =>
                {
                    b.HasOne("ImovelStand.Domain.Entities.Empreendimento", "Empreendimento")
                        .WithMany("Torres")
                        .HasForeignKey("EmpreendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empreendimento");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Venda", b =>
                {
                    b.HasOne("ImovelStand.Domain.Entities.Apartamento", "Apartamento")
                        .WithMany("Vendas")
                        .HasForeignKey("ApartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImovelStand.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartamento");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Apartamento", b =>
                {
                    b.Navigation("HistoricoPrecos");

                    b.Navigation("Reservas");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Empreendimento", b =>
                {
                    b.Navigation("Tipologias");

                    b.Navigation("Torres");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Tipologia", b =>
                {
                    b.Navigation("Apartamentos");
                });

            modelBuilder.Entity("ImovelStand.Domain.Entities.Torre", b =>
                {
                    b.Navigation("Apartamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
